/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary": "#006b5f",
        "surface-bright": "#f9f9ff",
        "inverse-primary": "#a7c8ff",
        "inverse-surface": "#263143",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005047",
        "primary": "#004482",
        "background": "#f9f9ff",
        "surface-container-highest": "#d8e3fb",
        "tertiary-fixed-dim": "#59dcb8",
        "on-secondary": "#ffffff",
        "surface-dim": "#cfdaf2",
        "on-background": "#111c2d",
        "surface-tint": "#0b5eaf",
        "primary-container": "#005bac",
        "on-primary-container": "#bdd5ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a7c8ff",
        "tertiary-container": "#006853",
        "secondary-container": "#8cf2e0",
        "inverse-on-surface": "#ecf1ff",
        "on-secondary-container": "#006f63",
        "on-error": "#ffffff",
        "on-surface": "#111c2d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#72d8c7",
        "on-primary-fixed-variant": "#004788",
        "on-surface-variant": "#424751",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#002018",
        "tertiary": "#004e3d",
        "surface-container-low": "#f0f3ff",
        "surface-variant": "#d8e3fb",
        "surface-container-high": "#dee8ff",
        "surface": "#f9f9ff",
        "on-primary-fixed": "#001b3b",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "outline-variant": "#c2c6d3",
        "tertiary-fixed": "#79f9d3",
        "on-tertiary-fixed-variant": "#005140",
        "secondary-fixed": "#8ef4e3",
        "on-secondary-fixed": "#00201c",
        "on-tertiary-container": "#69eac5",
        "surface-container": "#e7eeff",
        "outline": "#727783"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "gutter-sm": "1rem",
        "space-xs": "0.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "gutter": "1.5rem",
        "space-2xl": "3rem",
        "margin": "2rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "gutter-lg": "2rem"
      },
      fontFamily: {
        display: ["Public Sans", "Pretendard", "sans-serif"],
        "headline-lg": ["Public Sans", "Pretendard", "sans-serif"],
        "headline-md": ["Public Sans", "Pretendard", "sans-serif"],
        "headline-sm": ["Public Sans", "Pretendard", "sans-serif"],
        "body-lg": ["Public Sans", "Pretendard", "sans-serif"],
        "body-md": ["Public Sans", "Pretendard", "sans-serif"],
        "body-sm": ["Public Sans", "Pretendard", "sans-serif"],
        "label-lg": ["Public Sans", "Pretendard", "sans-serif"],
        "label-md": ["Public Sans", "Pretendard", "sans-serif"],
        "label-sm": ["Public Sans", "Pretendard", "sans-serif"],
        "data-metric": ["Public Sans", "Pretendard", "sans-serif"]
      },
      fontSize: {
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "data-metric": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
