import React, { useMemo, useState } from 'react';
import { MOCK_COMPANIES } from '../data/mockCompanies';

export const AdminCompaniesView: React.FC = () => {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'ALL' | 'COMPLETED' | 'REVIEW'>('ALL');
  const [selectedId, setSelectedId] = useState(MOCK_COMPANIES[0]?.company.id || '');
  const selected = MOCK_COMPANIES.find((item) => item.company.id === selectedId) || MOCK_COMPANIES[0];
  const companies = useMemo(() => MOCK_COMPANIES.filter((item) => {
    const text = [item.company.name, item.company.industry, item.company.location, ...item.company.keywords].join(' ').toLowerCase();
    const matchesQuery = text.includes(query.trim().toLowerCase());
    const matchesFilter = filter === 'ALL' || (filter === 'COMPLETED' ? item.analysis.status === 'COMPLETED' : item.analysis.status !== 'COMPLETED');
    return matchesQuery && matchesFilter;
  }), [filter, query]);

  return <div className="max-w-[1500px] mx-auto">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-7">
      <div><p className="text-xs font-bold text-blue-600 mb-2">기업 데이터 관리</p><h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-900">기업 관리</h1><p className="mt-2 text-sm text-slate-500">사업계획서 분석 결과와 기업별 지원·매칭 상태를 관리합니다.</p></div>
      <button type="button" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-blue-600 text-white text-sm font-bold"><span className="material-symbols-outlined text-base">person_add</span>기업 수동 등록</button>
    </div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6">{[
      ['전체 등록 기업', '248', '전분기 대비 12%', 'business'], ['AI 분석 완료', '251', '완료율 77.0%', 'smart_toy'], ['지원사업 매칭 후보', '142', '기업당 평균 3.4건', 'hub'], ['성과관리 대상', '38', '이번 달 제출 12건', 'monitoring'],
    ].map(([label, value, note, icon]) => <div key={label} className="bg-white border border-slate-200 rounded-xl p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-400">{label}</span><span className="material-symbols-outlined text-blue-600">{icon}</span></div><div className="text-2xl font-black text-slate-800 mt-3">{value}<span className="text-sm font-medium ml-1">개</span></div><div className="text-[11px] text-emerald-600 font-bold mt-1">{note}</div></div>)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1.5fr)_360px] gap-6 items-start">
      <section className="bg-white border border-slate-200 rounded-xl overflow-hidden">
        <div className="p-5 border-b border-slate-100 flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><h2 className="text-lg font-extrabold text-slate-900">등록 기업 목록 <span className="text-sm text-slate-400">{companies.length}건</span></h2><div className="flex gap-1 mt-3">{([['ALL', '전체'], ['COMPLETED', 'AI 분석 완료'], ['REVIEW', '검토 필요']] as const).map(([key, label]) => <button key={key} type="button" onClick={() => setFilter(key)} className={`px-3 py-1.5 rounded-full text-xs font-bold ${filter === key ? 'bg-blue-50 text-blue-600' : 'text-slate-400 hover:bg-slate-50'}`}>{label}</button>)}</div></div><label className="relative"><span className="material-symbols-outlined absolute left-3 top-2.5 text-slate-400 text-lg">search</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="기업명·산업·지역 검색" className="w-full lg:w-64 pl-9 pr-3 py-2 rounded-lg border border-slate-200 bg-slate-50 text-sm outline-none focus:border-blue-500 focus:bg-white" /></label></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-slate-50 text-[11px] text-slate-400"><tr><th className="px-5 py-3">기업명</th><th className="px-3 py-3">산업·소재지</th><th className="px-3 py-3">T/E/M</th><th className="px-3 py-3">핵심 병목</th><th className="px-3 py-3">상태</th></tr></thead><tbody className="divide-y divide-slate-100">{companies.map((item) => <tr key={item.company.id} onClick={() => setSelectedId(item.company.id)} className={`cursor-pointer hover:bg-slate-50 ${selected?.company.id === item.company.id ? 'bg-blue-50/60' : ''}`}><td className="px-5 py-4"><div className="font-bold text-sm text-slate-800">{item.company.name}</div><div className="text-[11px] text-slate-400 mt-1">{item.company.employees}명 · 매출 {item.company.revenue / 100}억원</div></td><td className="px-3 py-4"><div className="text-xs font-bold text-slate-600">{item.company.industry}</div><div className="text-[11px] text-slate-400 mt-1">{item.company.location}</div></td><td className="px-3 py-4 text-xs font-black text-blue-600">{item.analysis.temDiagnosis.technology.level} · {item.analysis.temDiagnosis.execution.level} · {item.analysis.temDiagnosis.market.level}</td><td className="px-3 py-4"><span className="px-2 py-1 rounded-full bg-rose-50 text-rose-600 text-[11px] font-bold">{item.analysis.primaryBottleneck}</span></td><td className="px-3 py-4"><span className={`px-2 py-1 rounded text-[11px] font-bold ${item.analysis.status === 'COMPLETED' ? 'bg-emerald-50 text-emerald-600' : 'bg-orange-50 text-orange-600'}`}>{item.analysis.status === 'COMPLETED' ? 'AI 분석 완료' : '검토 필요'}</span></td></tr>)}</tbody></table></div>
      </section>
      {selected && <aside className="bg-white border border-slate-200 rounded-xl p-5 sticky top-20"><div className="flex items-start justify-between border-b border-slate-100 pb-4"><div><span className="text-xs font-bold text-blue-600">선택 기업 상세</span><h2 className="text-xl font-black text-slate-900 mt-1">{selected.company.name}</h2><p className="text-xs text-slate-400 mt-1">{selected.company.businessNumber}</p></div><span className="w-10 h-10 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center"><span className="material-symbols-outlined">business</span></span></div><div className="grid grid-cols-3 gap-2 mt-5">{[['기술', selected.analysis.temDiagnosis.technology.level], ['실행', selected.analysis.temDiagnosis.execution.level], ['시장', selected.analysis.temDiagnosis.market.level]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><span className="text-[10px] text-slate-400">{label}</span><div className="text-xl font-black text-slate-800 mt-1">{value}</div></div>)}</div><div className="mt-5 rounded-lg bg-rose-50 border border-rose-100 p-4"><span className="text-xs font-bold text-rose-600">핵심 관리 병목</span><h3 className="font-bold text-slate-800 mt-1">{selected.analysis.bottlenecks[0]?.title || selected.analysis.primaryBottleneck}</h3><p className="text-xs text-slate-500 leading-5 mt-2">{selected.analysis.supportGapAnalysis}</p></div><div className="mt-5"><h3 className="text-sm font-bold text-slate-800">연계 지원사업</h3><ul className="mt-3 space-y-2">{selected.analysis.recommendedSupport.slice(0, 3).map((item) => <li key={item} className="flex gap-2 text-xs text-slate-600"><span className="material-symbols-outlined text-emerald-600 text-base">check_circle</span>{item}</li>)}</ul></div><button type="button" className="w-full mt-5 py-2.5 rounded-lg bg-blue-600 text-white text-xs font-bold">기업 상세 리포트 열기</button></aside>}
    </div>
  </div>;
};
